# Fire off a bunch of these with:
# find . -name kelvin.conf -execdir nq "make -f ../Makefile.common || touch MAKE-FAILED" \;
# Won't allow multiple simultaneous runs, but alas, if a run fails, leaves MAKE-RUNNING there.
# Clean it out with:
# find . -name MAKE-FAILED -execdir rm MAKE-RUNNING \;
# before you resubmit.

clean :
	- rm -rf *.out kelvin_*_memory.dat MAKE-* *.so compiled

all : 
ifeq ($(wildcard MAKE-RUNNING), MAKE-RUNNING)
	echo Run already in progress
else
	- rm -rf *.out kelvin_*_memory.dat MAKE-* *.so compiled
	- touch MAKE-RUNNING
	date >>runtimes ; time (~/kelvin/trunk/kelvin.x86_64-Linux kelvin.conf >kelvin.out 2>&1) 2>> runtimes
	perl ~/kelvin/trunk/utils/wordDiff.pl br.out br.out-baseline .00001
  ifeq ($(wildcard ppl.out),ppl.out)
	diff ppl.out ppl.out-baseline
  endif
        # Make sure we don't accumulate too much information
	- tail -1000 runtimes >fewerRuntimes
	- mv fewerRuntimes runtimes
	- rm MAKE-RUNNING
        # Here I _will_ grep kelvin\*version and put the results into some file
	- touch MAKE-GOOD-CURRENT
endif
