#include "mysql.h"

#define MAXSTMTLEN 256
#define MAXPARAMLEN 64

struct StudyDB {
  // Common...
  char role[MAXPARAMLEN];
  int inStudyId;
  char hostname[MAXPARAMLEN];
  char dBName[MAXPARAMLEN];
  char username[MAXPARAMLEN];
  char password[MAXPARAMLEN];
  MYSQL *connection;
  // Adhoc...
  char strAdhocStatement[MAXSTMTLEN];
  MYSQL_RES *resultSet;
  MYSQL_ROW row;
  // GetPedPosId...
  MYSQL_STMT *stmtGetPedPosId;
  MYSQL_BIND bindGetPedPosId[4];
  char strGetPedPosId[MAXSTMTLEN];
  char inPedigreeSId[16];
  int inChromosomeNo;
  double inRefTraitPosCM;
  MYSQL_BIND bindGetPedPosIdResults[1];
  int outPedPosId;
  // GetDLOD...
  MYSQL_STMT *stmtGetDLOD;
  MYSQL_BIND bindGetDLOD[15];
  char strGetDLOD[MAXSTMTLEN];
  int inPedPosId;
  double inDGF;
  double inLC1BigPen;
  double inLC1BigLittlePen;
  double inLC1LittleBigPen;
  double inLC1LittlePen;
  double inLC2BigPen;
  double inLC2BigLittlePen;
  double inLC2LittleBigPen;
  double inLC2LittlePen;
  double inLC3BigPen;
  double inLC3BigLittlePen;
  double inLC3LittleBigPen;
  double inLC3LittlePen;
  int inRegionNo;
  // GetDLOD results...
  MYSQL_STMT *stmtGetDLODResults;
  MYSQL_BIND bindGetDLODResults[3];
  char strGetDLODResults[MAXSTMTLEN];
  int outRegionId;
  int outMarkerCount;
  double outLOD;
  // GetWork...
  MYSQL_STMT *stmtGetWork;
  MYSQL_BIND bindGetWork[3];
  char strGetWork[MAXSTMTLEN];
  int inServerId;
  double inLowPosition;
  double inHighPosition;
  // GetDTParts...
  MYSQL_STMT *stmtGetDTParts;
  char strGetDTParts[MAXSTMTLEN];
  // GetWorkResults
  MYSQL_STMT *stmtGetWorkResults;
  MYSQL_BIND bindGetWorkResults[16];
  char strGetWorkResults[MAXSTMTLEN];
  char outPedigreeSId[16];
  double outPedTraitPosCM;
  double outDGF;
  double outLC1BigPen;
  double outLC1BigLittlePen;
  double outLC1LittleBigPen;
  double outLC1LittlePen;
  double outLC2BigPen;
  double outLC2BigLittlePen;
  double outLC2LittleBigPen;
  double outLC2LittlePen;
  double outLC3BigPen;
  double outLC3BigLittlePen;
  double outLC3LittleBigPen;
  double outLC3LittlePen;
  // PutWork...
  MYSQL_STMT *stmtPutWork;
  MYSQL_BIND bindPutWork[2];
  char strPutWork[MAXSTMTLEN];
  int inMarkerCount;
  double inLOD;
  // other...
  int bogusLODs;
  int realLODs;
};

