test :
	- rm -rf *.out
	@echo -e "\n\
    **** THIS TEST IS CURRENTLY DISABLED ****\n\
"
#	(time $(TEST_KELVIN) kelvin.conf) >kelvin.out 2>&1
#	perl $(KELVIN_ROOT)/utils/wordDiff.pl br.out br.out-baseline .000001
#	perl $(KELVIN_ROOT)/utils/wordDiff.pl ppl.out ppl.out-baseline .000001

clean :
	- rm -rf *.out *.so *memory.dat compiled
