#!/bin/bash -xe
# Copyright (C) 2020, 2022 Mathematical Medicine LLC
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
set -xe # Because it isn't enough for Darwin's cron for us to have it on the shebang

# This doesn't work deep under Make:alias log='$HOME/kit/bin/log'
export PATH=$HOME/kit/bin:$PATH # ...so this ought to do it

echo "`date`: Starting on $1"
export KELVIN_ROOT=$HOME/specific/trunk
export KELVIN_SCRIPT=$HOME/specific/trunk
export LD_LIBRARY_PATH=$KELVIN_ROOT/lib:${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH}
export OMP_NUM_THREADS=1
make clean
make $1


