#!/bin/bash -xe
# Copyright (C) 2012, 2020, 2022 Mathematical Medicine LLC
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Acquire the kelvin repo, build all flavors of kelvin, and test every bit of it and collect some
# performance statistics on 7 different platforms:
#
# - 64-bit Linux on our Levi-Montalcini cluster (our primary run environment)
# - 64-bit Linux on the Oakley cluster at the Ohio Supercomputer Center (our secondary run environment)
# - cygwin on exception under virtual Windows/Intel machine (compares to Linda's students)
# - Solaris 9 for SPARC on sparky (compares to Cinci Children's Hospital)
# - Solaris 10 for Intel on flair under VirtualBox
# - 32-bit Linux with old GCC on our testbed
# - 32-bit Mac OSX 10.5 on our Intel desktops
# - 32-bit Mac OSX 10.4 on the PowerPC testmac
# 
# Sits in the $HOME/specific subdirectory and is fired-up weekday evenings by a cron job (cygwin 
# version is run manually). E-mails me if there's a problem. The performance statistics are wrapped
# in SQL in the $HOME/specific directory in a file with date stamp for execution under MySQL.
#

trap onexit 0

function onexit() {
    local exit_status=${1:-$?}
    case $HOSTNAME in
	RES* ) # Anything provided by IS these days...
	    MAIL="o2mail.ass "
	    ;;
        sparky* ) # Solaris
            BASH_SOURCE=$0
            MAIL="mailx -s "
	    ;;
	Deimos|exception*|flair* )  # VMs, cygwin, other orphans
            MAIL="perl $HOME/kit/bin/NCHSendMail.pl -s "
	    ;;
        * )  # Trust mailer configuration on everything else (hah!)
	    MAIL="mail -r wvc@MathMed.org -s "
	    ;;
    esac
    if test $exit_status -ne 0 ; then

	echo Exiting $BASH_SOURCE at `date` with status of $exit_status
	cp $BASH_SOURCE.log $HOME/specific/kelvin_TESTED.BAD
	echo "Sending mail with [${MAIL}], [${BASH_SOURCE}] and [${HOSTNAME}]"
	${MAIL} "$BASH_SOURCE on $HOSTNAME failed with status $exit_status" wvc@MathMed.org </dev/null
    else
	${MAIL} "$BASH_SOURCE on $HOSTNAME succeeded" wvc@MathMed.org </dev/null
    fi
    exit $exit_status
}
set -xe # Because it isn't enough for Darwin's cron for us to have it on the shebang

# This doesn't work deep under Make:alias log='$HOME/kit/bin/log'
export PATH=$HOME/kit/bin:$PATH # ...so this ought to do it

echo `date`: Starting
export KELVIN_ROOT=$HOME/source/kelvin
export KELVIN_SCRIPT=$HOME/source/kelvin
export LD_LIBRARY_PATH=$KELVIN_ROOT/lib:${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH}
cd $HOME/source/kelvin

make clean

# GSL tends to wander, so make sure that INCDIR and LIBDIR are set if needed
echo `date`: Full build with INCDIR as $INCDIR and LIBDIR as $LIBDIR

make kelvin-no_GSL # Need to do this first because it removes kelvin!
make kelvin
make seq_update/calc_updated_ppl
echo `date`: Basic tests
export OMP_NUM_THREADS=1
make test

echo `date`: Fixed VS dynamic grid testing
make test-FIXED

echo "`date`: LKS programs & DB-only testing - not current scripting"
# Make databaseSupport.c tolerable for frikin' new MySQL development
perl -p -i -e 's/my_bool/bool/g' database/databaseSupport.c
make kelvin-study
make clean
make test-LKS || echo "Cannot make test-LKS"

echo `date`: Polynomial compilation tests
make kelvin-POLYCOMP_DL
make kelvin-POLYUSE_DL
make kelvin-POLYCODE_DL_FAKEEVALUATE_SSD
export OMP_NUM_THREADS=8
make test-USE_DL

# Grab performance data while we can...
cd $HOME/specific
find . \( -name kelvin\*.log -or -name cycle.out \) -exec egrep -i -e "[kK]elvin.* V[0-9\.]+ edit [0-9\.]+|^real\s+[0-9]+"  \{\} /dev/null \; \
    | perl -S -n logStats.pl >>Inserts_$HOSTNAME-`date +"%Y%m%d"`.sql
for i in Inserts_*sql; do cat "${i}" | mysql --defaults-extra-file=~/DATABASE-TO-USE.cnf log; rm "${i}"; done

