test :
	- rm -rf *.out
	@echo -e "\n\
    **** THIS TEST IS CURRENTLY DISABLED ****\n\
"

	#- rm -f ped.post.counted ped.post.counts *.out *pass*
	#(time $(KELVIN_SCRIPT) kelvin.conf) >kelvin.out 2>&1
	#perl $(KELVIN_ROOT)/utils/wordDiff.pl br.out br.out-baseline .000001
	#perl $(KELVIN_ROOT)/utils/wordDiff.pl ppl.out ppl.out-baseline .000001
	#perl $(KELVIN_ROOT)/utils/wordDiff.pl mod.out mod.out-baseline .000001
	#(time $(KELVIN_SCRIPT) kelvin.conf --SkipAnalysis) >kelvin.out 2>&1
	#diff -ib ped.post.pass0.counted ped.post.0.counted-baseline
	#diff -ib ped.post.pass0.counts ped.post.0.counts-baseline
	#diff -ib ped.post.pass1.counted ped.post.1.counted-baseline
	#diff -ib ped.post.pass1.counts ped.post.1.counts-baseline

clean :
	- rm -f ped.post.counted ped.post.counts *.out *pass*

