"""Contains strings used as names for the various xml components in a .grx file"""

hlines = 'horizontal_lines'
hlineValue = 'value'
comments = 'comments'

config = 'configuration'
config_title = 'graph_title'
config_xlabel = 'x-axis_label'
config_ylabel = 'y-axis_label'
config_bgcolor = 'background_color'
config_showLegend = 'show_legend'
config_showLineSetsInLegend = 'show_linesets_in_legend'
config_showLegendFrame = 'show_legend_frame'
config_legendPosition = 'legend_position'
config_titleSize = 'title_text_font_size'
config_axisSize = 'axis_labels_font_size'
config_xmin = 'view_xmin'
config_xmax = 'view_xmax'
config_ymin = 'view_ymin'
config_ymax = 'view_ymax'
config_annPPLPrec = 'annotation_ppl_precision'
config_annPosPrec = 'annotation_pos_precision'
config_isAnnSameColor = 'annotation_same_color_as_line'
config_allowDuplicates = 'chr_label_allow_duplicates'

anns = 'annotations'
ann = 'annotation'
ann_x = 'x'
ann_y = 'y'
ann_text = 'label'
ann_text_pos = 'label_pos'
ann_isPeak = 'is_peak'
ann_isTrough = 'is_trough'
ann_lineId = 'line_id'
ann_autoLayout = 'auto_layout'

lines = 'lines'
lineset = 'line_set'
lineset_id = 'id'
lineset_name = 'name'
lineset_color = 'color'
lineset_thickness = 'thickness'
lineset_style = 'line_style'
lineset_marker = 'marker'
lineset_marker_size = 'marker_size'
line_group = 'line_group'
line = 'line'
line_id = 'id'
line_set_id = 'line_set_id'
line_name = 'name'
line_number = 'number'
line_color = 'color'
line_thickness = 'thickness'
line_style = 'line_style'
line_marker = 'marker'
line_marker_size = 'marker_size'
line_gene_markers = 'gene_markers'
line_gene_marker = 'gene_marker'
line_gene_marker_id = 'id'
line_gene_marker_group = 'group_id'
line_pos = 'positions'
line_ppl = 'ppls'
line_metadata = 'metadata'
line_metadata_set = 'metadata_set'
line_metadata_value = 'metadata_value'

gene_markers_groups = 'gene_markers_groups'
gene_markers_group = 'gene_markers_group'
gene_markers_group_id = 'id'
gene_markers_group_name = 'name'
gene_markers_group_color = 'color'
gene_markers_group_symbol = 'symbol'
gene_markers_group_size = 'size'

gene_markers = 'gene_markers'
gene_markers_id = 'id'
gene_markers_pos = 'positions'

