"""Specifies the types of tokens able to be produced"""

COMMENT = "comment"
ID = "word"
NUMBER = "number"
NEWLINE = "newline"
ENDOFINPUT = "end of input"
UNKNOWN = "unknown word"
SEMICOLON = "semicolon"
OPERATOR = "operator"
